Repository front-end-by-rimantas/18-grupe-portfolio-saas-one, pull requests merged in 2020-10, with the labels that each got.

#16 Update README.md
  README.md
Labels: documentation

#26 Hero
  css/custom.css
  css/hero.css
  css/main.css
  css/reset.css
  img/admin.png
  img/hero-bg.png
  index.html
Labels: CSS, HTML

#28 Home page about
  css/FAQ.css
  css/custom.css
  css/feature.css
  css/footer.css
  css/homepage-about.css
  css/projects.css
  css/testimonals.css
  index.html
Labels: CSS, HTML

#30 Hero: responsive design
  css/custom.css
Labels: responsive design

#29 App section
  css/app.css
  css/custom.css
  img/mobile-1.png
  img/mobile-2.png
  index.html
Labels: CSS, HTML

#31 Update README.md
  README.md
Labels: documentation

#32 Hero: White button hover
  css/custom.css
Labels: CSS

#34 Testemonials
  css/custom.css
  img/boy.png
  img/mini-test-bg.png
  img/testimonials-bd.png
  index.html
Labels: CSS, HTML

#33 FAQ
  css/custom.css
  index.html
Labels: CSS, HTML

#37 Footer
  css/custom.css
  img/logo.svg
  index.html
Labels: CSS, HTML

#36 Our team
  css/custom.css
  img/our-team-bg.jpg
  img/team/1.png
  img/team/2.png
  img/team/3.png
  index.html
Labels: CSS, HTML, help wanted, question

#66 Grid system
  css/custom.css
  css/layout.css
  css/our-team.css
  index.html
Labels: CSS, HTML, responsive design

#68 Update Readme.md
  README.md
Labels: documentation

#70 Folder structure
  js/components/empty.txt
  js/data/empty.txt
Labels: documentation

#71 Update main.js
  js/main.js
Labels: documentation

#72 Js about
  index.html
  js/components/empty.txt
  js/components/home-about/generateSingleHomeAbout.js
  js/components/home-about/isValidAbout.js
  js/components/home-about/renderHomeAbout.js
  js/data/empty.txt
  js/data/homeAboutData.js
  js/main.js
Labels: JS

#74 Js feature goodone
  index.html
  js/components/feature/generateSingleFeature.js
  js/components/feature/isValidFeature.js
  js/components/feature/renderFeature.js
  js/data/features.js
  js/main.js
Labels: JS

#75 JS FAQ
  css/custom.css
  index.html
  js/components/faq/generateSingleFAQ.js
  js/components/faq/isValidFAQ.js
  js/components/faq/renderFAQ.js
  js/data/faq.js
  js/main.js
Labels: JS

#77 bg animations
  css/custom.css
  css/main.css
  img/shape-oval.png
  img/shape-plus.png
  img/shape-square.png
  img/shape-triangle.png
  index.html
Labels: CSS

#76 basic multipage structure
  about/index.html
  blog/index.html
  contact/index.html
  index.html
  portfolio/index.html
Labels: HTML

#78 Js header
  css/custom.css
  index.html
  js/data/header.js
Labels: CSS, HTML

#79 Js faq
  js/components/faq/generateSingleFAQ.js
  js/components/faq/renderFAQ.js
Labels: JS

#81 Formating
  js/components/faq/isValidFAQ.js
  js/components/feature/isValidFeature.js
  js/components/feature/renderFeature.js
  js/components/home-about/isValidAbout.js
  js/components/home-about/renderHomeAbout.js
  js/data/faq.js
Labels: documentation

#82 App section
  css/custom.css
Labels: responsive design

#84 Updated readME re badges
  README.md
Labels: documentation

#83 Js address
  css/custom.css
  index.html
  js/components/address/isValidAddress.js
  js/components/address/renderAddress.js
  js/components/address/renderSingleAddress.js
  js/data/ourAddressData.js
  js/main.js
Labels: JS

#85 Transitions on page load
  contact/index.html
  css/main.css
Labels: CSS

#86 Js ourteam
  css/custom.css
  index.html
  js/components/ourTeam/generateSingleOurTeam.js
  js/components/ourTeam/isValidTeam.js
  js/components/ourTeam/renderOurTeam.js
  js/components/testimonials/genereteSingleTestimonial.js
  js/components/testimonials/isValidTestimonial.js
  js/components/testimonials/renderTestimonial.js
  js/data/ourTeamData.js
  js/data/testimonials.js
  js/main.js
Labels: JS, bug

#89 Js footer
  index.html
  js/components/footer/generateSingleFooter.js
  js/components/footer/isValidFooter.js
  js/components/footer/renderFooter.js
  js/data/features.js
  js/data/footer.js
  js/main.js
Labels: JS

#92 Multipages validation update
  about/index.html
  contact/index.html
  css/custom.css
  index.html
  js/components/address/renderAddress.js
  js/components/faq/renderFAQ.js
  js/components/feature/renderFeature.js
  js/components/home-about/renderHomeAbout.js
  js/components/ourTeam/renderOurTeam.js
Labels: JS

#91 Back to top
  css/main.css
  index.html
  js/components/back-to-top.js
  js/main.js
Labels: CSS, HTML

#90 Js testimonials
  index.html
  js/components/testimonials/generateSingleTestimonial.js
  js/components/testimonials/genereteSingleTestimonial.js
  js/components/testimonials/isValidTestimonial.js
  js/components/testimonials/renderTestimonial.js
  js/data/testimonials.js
  js/main.js
Labels: JS

#93 main JS structure update
  css/custom.css
  js/main.js
Labels: documentation

#106 Our-Team update + header links
  css/custom.css
  img/team/4.png
  index.html
  js/components/ourTeam/generateSingleOurTeam.js
  js/components/ourTeam/renderOurTeam.js
  js/data/header.js
  js/data/ourTeamData.js
  pages/our team/index.html
Labels: CSS, HTML, JS
